Module Variables
    'Variables factura Electronica
    Public LimFac As Decimal
    Public SalFac As Decimal
    Public DetCant As String
    Public CantProd As Integer
    Public CuitRem As String
    Public CliTick As String
    Public DirTick As String
    Public CiuTick As String
    Public CuitTick As String
    Public CivaTick As String
    Public FechIm As String
    Public concepto, tipo_doc, nro_doc, _
    cbt_desde, cbt_hasta, imp_total, imp_tot_conc, imp_neto, _
    imp_iva, imp_trib, imp_op_ex, fecha_cbte, fecha_venc_pago, _
    fecha_serv_desde, fecha_serv_hasta, _
    moneda_id, moneda_ctz
    Public CanIm As String
    Public PunIm As String
    Public PtoIm As String
    Public NumDbto As Integer
    Public ruta As String = System.Environment.CurrentDirectory.ToString
    Public LetrComp As String
    Public Exp As Integer
    Public Iva10 As Decimal
    Public Iva21 As Decimal
    Public AlicMi As String
    Public CivaEnc As String
    Public Lfantacia As String
    Public Ser As Integer
    Public Tocken As String
    Public Sign As String
    Public Pv As String
    Public Certif As String
    Public ClavePiv As String
    Public VtoCae As String
    Public Cuit_Em As String
    Public cbte_nro, cae
    Public fecha_vto_cae As String
    Public base_imp
    Public Dcuit As String
    Public Mcuit As String
    Public Icuit As String
    Public IdAlic As Integer
    Public CAli As String
    Public Empresa As String
    Public DirEm As String
    Public CiuEm As String
    Public IbEm As String
    Public CivEm As String
    Public InAcEm As String
    Public CuitEm As String
    Public Ob1 As String
    Public Ob2 As String
    Public Ob3 As String
    Public Numcop As Integer
    Public AlicIm As Integer
    Public Civa As String
    Public EsBr As Integer
    Public Largo As Integer
    Public Primero As Integer
    Public BarId As String
    Public Entero As String
    Public Decim As String
    Public BPro As String
    Public Btar As String
    Public DesAic As Decimal
    Public Email As String
    Public motivo_obs As String
    Public Fech As Date
    Public FechCta As Date
    Public tipo_cbte As String
    Public punto_vta As String
    Public WSAA As Object
    Public Path As String
    Public tra As String
    Public cms As String
    Public ta As String
    Public wsdl As String
    Public proxy As String
    Public cache As String
    Public certificado As String
    Public claveprivada As String
    Public ok
    Public BCli As String
    Public MaxFl As Integer
    Public Lin As Integer
    Public Net As Decimal
    Public Iv As Decimal
    Public Tot As Decimal
    Public Tot1 As Decimal
    '**************
    'Public Idpc As Integer
    Public IdCu As Integer
    Public EsCiu As Integer
    Public Rst As String
    Public RspFis As String
    Public RspImp As String
    Public Fecha As String
    Public Hora As String
    Public Comando As String
    Public IdIva As Integer
    Public AlicDisc As Double
    Public Dlin As Integer
    '********************
    Public Bart As String
    Public respuesta As New System.Text.StringBuilder
    Public Ent As Decimal
    Public Total As Decimal
    Public EsCom As Integer
    Public Punit1 As Decimal
    Public Ptotal As Decimal
    Public PtotalM As Decimal
    Public TotalGral As Decimal
    Public Pcosto As Decimal
    Public Cantidad As Decimal
    Public Util As Decimal
    Public Util1 As Decimal
    Public Pneto As Decimal
    Public EsRp As Integer
    Public IdOr As Integer
    Public IdOrd As Integer
    Public IdOrt As Integer
    Public Ord As Integer
    Public Stock As Integer
    Public Pfinal As Decimal
    Public EsMar As Integer
    Public EsFam As Integer
    Public Count As Integer
    Public LinCom As Integer
    Public Linea1 As String
    Public Linea2 As String
    Public Linea3 As String
    Public Linea4 As String
    Public SalOld As Decimal
    Public EntAnt As Decimal
    Public SalAnt As Decimal
    Public DesAn As Date
    Public HasAn As Date
    Public HasAn1 As String
    Public Saldo As Decimal
    Public Num As String
    Public Lnum As String

    Public Lpv As String
    Public LidCl As String
    Public IdTp As Integer
    Public LidTp As String
    Public currentrow As Integer
    Public EntAc As Decimal
    Public EntAc1 As Decimal
    Public Importe As Decimal
    Public Fech1 As Date
    Public FecVen As Date
    Public FecVen1 As Date
    Public EsVenta As Integer
    Public Cventa As String
    Public IdEnc As Integer
    Public Clave As String
    Public Idcl As Integer
    Public Iva As Decimal
    Public Neto As Decimal
    Public Punt As Decimal
    Public AlIv As Decimal
    Public Iint As Decimal
    Public Entrega As Decimal
    Public Articulo As String
    Public IdPr As Integer
    Public IdFm As Integer
    Public IdMr As Integer
    Public Alic As Decimal
    Public Alic1 As Decimal
    Public NumFac As Integer
    Public Barra As String
    Public BarFac As String
    Public BlNg As Integer
    Public EsCl As Integer
    Public EsPr As Integer
    Public EsAr As Integer
    Public EsCv As Integer
    Public Linea As Integer
    Public Id As Integer
    Public Tabla As String
    Public Campo As String
    Public valor As Decimal
    Public MiClase As New Conexion
    Public misdatos As New DataSet()
    Public Mensaje As MsgBoxResult
    Public EsOr As String
    Public IdCiva As Integer

    Public NetT As Decimal
    Public IvT As Decimal
    Public ToTT As Decimal
    Public Fact As Integer
    Public Puerto As Integer
    Public sCmd As String
    Public ScmdExt As String
    Public bAnswer As Boolean
    Public Can As String
    Public DCn As String
    Public Ecn As String
    Public Cant As String
    Public PuntS As String
    Public Dpn As String
    Public Epn As String
    Public Punt1 As Decimal
    Public AlicS As String
    Public Dal As String
    Public Eal As String
    Public Al As String
    Public nError As Long
    Public IdIv As String
    Public TipCu As String
    Public PuerImp As String
    Public Vi As Integer
    Public Vf As Integer
    Public IdAct As Integer
    Public Cuit As String
    Public Cadena As String
    Public Pc As Integer
    Public Mes As String
    Public Año As String
    Public Desde As Date
    Public Ds As Date
    Public Hasta As Date
    Public startDate As Date = Date.Today
    Public EsPago As Integer
    Public LCom As Integer
    Public TotPago As Decimal
    Public TotFac As Decimal
    Public Dln As Integer
    Public Comprobante As String
    Public NumPag As Integer
    Public ImPag As Decimal
    Public IdCom As Integer
    Public AbUn As String
    'Public Tot As Decimal
    Public Canti As Decimal
    Public Ent1 As Decimal
    Public Ncom As Integer
    Public NumFc As String
    Public Fpv As String
    Public FNum As String
    Public TotalE As Decimal
    Public TotalF As Decimal
    Public SumDebe As Decimal
    Public SumHaber As Decimal
    Public Pcos As Decimal
    Public Pcos1 As Decimal
    Public CosTot As Double
    Public UUtil As Double
    Public UtilNet As Double
    Public UtilTot As Double
    Public CosDolar As Double
    Public Cambio As Double
    Public interes As Decimal
    Public TotFin As Decimal
    Public TFin As Decimal
    Public NumCom As Integer
    Public NumCuo As Integer
    Public VenCuo As Date
    Public ImpCuo As Decimal
    Public DiasFin As Integer
    Public SalCuo As Decimal
    Public NetCuo As Decimal
    Public TotCuo As Decimal
    Public TotInt As Decimal
    Public Cuota As Decimal
    Public Verif As Integer
    Public Descu As Decimal
    Public TotDesc As Decimal
    Public IdPrv As Integer
    Public EsPrv As Integer
    Public Cpostal As String
    Public EsPag As Integer
    Public Sal As Integer
    Public SalNc As Decimal
    Public fila As Integer
    'Public Ent As Decimal
    Public Cnd As String
    Public Tel1 As String
    Public Tel2 As String
    Public Cp As String
    Public DPun As Decimal
    Public BsDt As String
    Public IdCuen As Integer
    Public FechCh As Date
    Public Dolar As Decimal
    Public TTotal As Decimal
    Public CmIva As String
    Public EntrPag As Decimal
    Public IdCl1 As Integer
    Public FCA As String
    Public Fc As Date
    Public Fc1 As Date
    Public Fcp As String
    Public FcD As String
    Public FcH As String
    Public FDes As String
    Public FHas As String
    Public PCli As String
    Public Pban As String
    Public IdCh As String
    Public IdCh3 As Integer
    Public Lcoun As Integer
    Public EsAgr As Integer
    Public Pr As Integer
    Public IdUs As Integer
    Public PuerNeg As String
    Public Usuario As String
    Public UsuCar As String
    Public PswCar As String
    Public Psw As String
    Public Br As Integer
    Public SalMax As Decimal
    Public DesRs As String
    Public HasRs As String
    Public Lf As Integer
    Public ErrTm As Integer
    Public FcTm As Date
    Public IdCiu As Integer
    Public EsNeg As String
    Public PCosCom As Decimal
    Public IvTot As Decimal
    Public Stk As Integer
    Public Impresora As String
    Public Obs As String
    Public obs_comerciales As String
    Public Abn As String
    Public Bold As String
    Public italic As String
    Public underline, foreground, background, align, prioridad, papel, orientacion, num_copias, lineas_max, qty_pos, salida, imprimir, NomArc, tipo As String

End Module
